#!/bin/bash
#SBATCH --job-name=checkv
#SBATCH --output=/home/yc1201/viral_genomics/checkv-%j.out
#SBATCH --error=/home/yc1201/viral_genomics/checkv-%j.err
#SBATCH --time=03:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=16G
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=yc1201@georgetown.edu

# ==== Load checkv program module (students: no need to change) ====

module load checkv


# ==== Set variables, paths, and filenames (students: edit this block!) ====

CHECKVDB="/home/yc1201/viral_genomics/checkv/checkv-db-v1.5"

SAMPLE_ID="vOTUs"
INPUT="/home/yc1201/viral_genomics/clustering/luby_dori_votus_final.fna"
OUTDIR="/home/yc1201/viral_genomics/checkv/${SAMPLE_ID}"

mkdir -p "${OUTDIR}"


# ==== run checkv (students: no need to change. The second line is the command) ====
echo "Running CheckV on ${INPUT}"
checkv end_to_end "${INPUT}" "${OUTDIR}" -d "${CHECKVDB}" -t ${SLURM_CPUS_PER_TASK}
echo "Done."

