#!/bin/bash #SBATCH --job-name=megahit_SRR699601     #how job appears in the queue
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=03:00:00
#SBATCH --output=/home/yc1201/viral_genomics/megahit/megahit_test1.%j.out
#SBATCH --error=/home/yc1201/viral_genomics/megahit/megahit_test1.%j.err

#note %j = job ID

# Load mamba/conda module (students: no need to change) 

module load mamba source 
(mamba info --base)/etc/profile.d/conda.sh

#Activate the environment where you had MEGAHIT installed conda activate megahit-env

# Set paths and filenames
#Directory where the cleaned reads live 

READDIR=/home/yc1201/viral_genomics/trimmed_reads

#Input read files (paired-end) 
READ1=${READDIR}/EC-12_R1_trmPE5.fq.gz 
READ2=${READDIR}/EC-12_R2_trmPE5.fq.gz

OUTDIR=/home/yc1201/viral_genomics/megahit/megahit_out

#==== Run MEGAHIT ====

megahit
-1 ${READ1}
-2 ${READ2}
-t ${SLURM_CPUS_PER_TASK}
-o ${OUTDIR}

echo "Done. Contigs should be in: ${OUTDIR}/final.contigs.fa"
